site_name: My Docs
nav:
  - Home: index.md
  - Tools:
    - Mkdocs Usage: tools/mkdocs.md
    - MkSlides Usage: tools/mkslides.md
  - Notes:
    - RF Basics: notes/rf_basics.md
    - Rust Basics: notes/rust_basics.md
    - CPU Basics: notes/cpu_basics.md
    - AI Basics: notes/ai_basics.md
    - Wireless Comm: notes/wireless_comm.md
  - Linux:
    - Kdump:
      - Kdump Usage: linux/kdump/kdump_usage.md
  - Wlan:
    - IEEE 802.11b:
      - Contents: wlan/ieee80211b/contents.md

theme:
  name: material